proxcity_app/__init__.py
from dotenv import load_dotenv
import os
from flask import Flask
from flask_bcrypt import Bcrypt
from flask_pymongo import PyMongo

load_dotenv()

app = Flask(__name__)
app.config["MONGO_URI"] = os.getenv('MONGO_URI')
app.secret_key = os.getenv('SECRET_KEY')

mongo = PyMongo(app)
bcrypt = Bcrypt(app)


from proxcity_app.routes import auth, main
app.register_blueprint(main)
app.register_blueprint(auth)

proxcity_app/routes.py
from flask import (
    request,
    redirect,
    render_template,
    url_for,
    Blueprint,
    session,
    flash
)
from flask_pymongo import PyMongo
from bson.objectid import ObjectId
from pymongo import MongoClient
from dotenv import load_dotenv
from pprint import PrettyPrinter
from operator import itemgetter
import datetime
import requests
import json
import os
from proxcity_app import bcrypt, mongo, app

##########################################
#                  Setup                 #
##########################################

load_dotenv()
CLIENT_ID = os.getenv('CLIENT_ID')
CLIENT_SECRET = os.getenv('CLIENT_SECRET')

pp = PrettyPrinter(indent=4)

main = Blueprint("main", __name__)
auth = Blueprint("auth", __name__)


##########################################
#           Session Config               #
##########################################

@app.before_request
def before_request():
    session.permanent = True
    app.permanent_session_lifetime = datetime.timedelta(minutes=15)
    session.modified = True


##########################################
#              Main Routes               #
##########################################

@main.route('/')
def home():
    '''Display homepage'''
    return render_template('home.html')


@main.route('/about')
def about():
    '''Display about page'''
    return render_template('about.html')


@main.route('/user', methods=["GET", "POST"])
def user():
    '''Display User Page'''
    if 'email' in session:
        user = mongo.db.users.find_one({'email': session['email']})

        if request.method == "GET":
            # Query the db for favorites and user data
            favorites = list(mongo.db.favorites.find({'user_id': user['_id']}))
            print(favorites)
            context = {
              'user': user,
              'favorites': favorites
            }
            return render_template('user.html', **context)
        else:
            # Add new favorite to user in db and display user page
            favorite = {
               'name': request.form.get("name"),
               'address': request.form.get('address'),
               'description': request.form.get('description'),
               'photo_path': request.form.get('photo_path'),
               'user_id': user['_id']
            }
            mongo.db.favorites.insert_one(favorite)

            return redirect(url_for('main.user'))
    else:
        return redirect(url_for('auth.login'))


@main.route('/results')
def results():
    '''Display result page'''
    query = request.args.get("search-query")
    city = request.args.get("city")
    zipcode = request.args.get("zipcode")
    if not zipcode:
        flash("Please enter a zipcode")
        return render_template('home.html')
    # Looking up City and State using Ziptastic api
    zipurl = "http://ZiptasticAPI.com/" + str(zipcode)
    zip_json = requests.get(zipurl).json()
    # Getting city and state from result json
    city = zip_json["city"]
    state = zip_json["state"]
    location = f"{city}, {state}"

    # Foursquare places api url
    url = "https://api.foursquare.com/v2/venues/search"
    # Parameters for the venues api
    params = {
        "client_id": CLIENT_ID,
        "client_secret": CLIENT_SECRET,
        "query": query,
        "near": location,
        "v": 20210201,
        "limit": 4
    }

    results_json = requests.get(url, params=params).json()
    results = results_json['response']['venues']

    # Gets venue ids for additional info
    venue_ids = []
    for venue in results_json['response']['venues']:
        venue_ids.append(venue['id'])

    desc_params = {
        "client_id": CLIENT_ID,
        "client_secret": CLIENT_SECRET,
        "v": 20210201
    }

    # Gets picture and description of each location
    descriptions = []
    photos = []
    photo_prefix = 'https://fastly.4sqi.net/img/general/300x300'
    for venue_id in venue_ids:
        description_url = f"https://api.foursquare.com/v2/venues/{venue_id}"
        description_results = requests.get(
            description_url, params=desc_params).json()
        # pp.pprint(description_results)
        # Tries to get picture and description
        try:
            description = description_results['response']['venue'][
                'description']
        # Uses a placeholder if info does not exist
        except KeyError:
            description = "No Description Given"
        descriptions.append(description)
        try:
            photo = photo_prefix + description_results[
                'response']['venue']['bestPhoto']['suffix']
        except KeyError:
            photo = url_for('static', filename='Logo.png')
        photos.append(photo)

    context = {
        'results': results,
        'num_venues': len(results),
        'photos': photos,
        'desc': descriptions
    }
    return render_template('results.html', **context)


@main.route('/delete', methods=['POST'])
def delete():
    """remove favorite from user"""
    item = request.form.get('id')
    mongo.db.favorites.delete_one(
        {'_id': ObjectId(item)}
    )
    return redirect(url_for('main.user'))


##########################################
#             Auth Routes                #
##########################################

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    '''Display signup page'''
    if 'email' in session:
        return redirect(url_for('main.home'))

    if request.method == 'GET':
        return render_template('signup.html')

    if request.method == 'POST':
        email, name, password = itemgetter(
            'email', 'name', 'password')(request.form)

        # Form input sanitization
        if email is None or type(email) is not str or \
                name is None or type(name) is not str or \
                password is None or type(password) is not str:
            flash('ERROR: Form input is not in the correct format')
            return redirect(url_for('auth.signup'))

        # Check if the user already exists in the database, if so go to login
        user = mongo.db.users.find_one({'email': email})

        if user is not None:
            flash('ERROR: User already exists in the database.')
            return redirect(url_for('auth.login'))

        # Insert the user into the database
        hashed_password = bcrypt.generate_password_hash(
            password).decode('utf-8')
        session['email'] = email

        new_user = {
            'email': email,
            'name': name,
            'password': hashed_password
        }

        mongo.db.users.insert_one(new_user)

        return redirect(url_for('main.home'))


@auth.route('/login', methods=['GET', 'POST'])
def login():
    '''Display login page'''
    if 'email' in session:
        return redirect(url_for('main.home'))

    if request.method == 'GET':
        return render_template('login.html')

    if request.method == 'POST':
        email, password = itemgetter('email', 'password')(request.form)

        # Form input sanitization
        if (
            email is None or type(email) is not str or
            password is None or type(password) is not str
           ):
            flash('ERROR: Form input is not in the correct format')
            return redirect(url_for('auth.login'))

        user = mongo.db.users.find_one({'email': email})

        # If the user is not found in the database
        if user is None:
            flash('ERROR: User not found, please signup')
            return redirect(url_for('auth.signup'))

        # If the passwords do not match
        if not bcrypt.check_password_hash(user['password'], password):
            flash('ERROR: Password is incorrect')
            return redirect(url_for('auth.login'))

        session['email'] = email
        flash('Successfully logged in!')
        return redirect(url_for('main.home'))


@auth.route('/logout', methods=['GET'])
def logout():
    session.pop('email', None)
    return redirect(url_for('auth.login'))

proxcity_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<main>
  <!-- ABOUT US -->
  <div id="about">
    <div class="container text-center">
      <h1 class="title">About Us</h1>
      <div class="row">
        <div class="col-md-4 d-flex justify-content-center align-items-center">
          <p class="story m-2">
            <img
              class="p-2"
              src="{{url_for('static', filename='Logo.png')}}"
              alt="Logo"
              width="150"
              ,
              height="150"
            />
            <br /><br />
            PROXCITY is a simple and easy way to find local businesses
            <br /><br />
            During the covid pandemic, small/medium local businesses suffered greatly.
            So we thought, why don't we make it easier for them to get noticed? 
            This project is aimed at helping local businesses market their name by making 
            it easier for users <b>"Find, Help, and Save"</b> them.
            <br><br>
            Be sure to “Find, Help, and Save” a local business in your city close to your proximity!
          </p>
        </div>

        <div class="col-md-8">
          <img src="/static/about.jpg" alt="" class="w-100" />
        </div>
      </div>
    </div>
  </div>
  <!-- End Abous Us -->
</main>
{% endblock %}

proxcity_app/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="/static/Logo2.png">

  <title>ProxCity</title>

  <!-- BOOTSTRAP STYLESHEET LINK-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <!-- BOOTSTRAP THEME -->
  <link rel="stylesheet" href="https://bootswatch.com/4/lux/bootstrap.min.css">
  <!-- CUSTOM STYLES -->
  <link rel="stylesheet" href="/static/style.css">
  <!-- AOS CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
</head>

<body>
  <div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog text-center">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-body">
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                <ul class=flashes>
                    {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                {% endwith %}
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
  </div>
  <!--  HOME NAV BAR -->
  <nav class="navbar bg-light navbar-dark navbar-expand-lg">
    <div class="container">
      <a href="/" class="navbar-brand">
        <img src="{{url_for('static', filename='Logo2.png')}}" alt="" width="75", height="75">
      </a>
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <!-- Home Route -->
          <li class="nav-item">
            <a href="{{ url_for('main.home') }}">
              Home
            </a>
          </li>
          <!-- About Route -->
          <li class="nav-item">
            <a href="{{ url_for('main.about') }}">
              About
            </a>
          </li>
          {% if 'email' in session and session['email'] is not none and session['email'] %}
            <!-- User Route -->
          <li class="nav-item">
            <a href="{{ url_for('main.user') }}">
              Favorites
            </a>
          </li>
          <!-- Logout Route -->
          <li class="nav-item">
            <a href="{{ url_for('auth.logout') }}">
              Logout
            </a>
          </li>
          {% else %}
          <!-- Login Route -->
          <li class="nav-item">
            <a href="{{ url_for('auth.login') }}">
              Login
            </a>
          </li>
          <!-- Signup Route -->
          <li class="nav-item">
            <a href="{{ url_for('auth.signup') }}">
              Signup
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <!-- End Navbar -->

  <!-- MAIN CONTENT -->
  <div class="main-content">
    {% block content %}
    {% endblock %}
  </div>  
  <!-- End Main Content -->

 
  <!--FOOTER-->  
  <footer>
    <h3>PROXCITY by <span>Lucky 7</span></h3>
    <p> Source Code:</p>
    <div id = "find">
        <a href="https://github.com/Kou-kun42/proxcity" class="github" title="Github">
            <i class="fa fa-github fa-3x"></i>
        </a>
    
    </div>
  </footer>
  <!-- End Footer -->
  <!-- End Footer -->

<!-- AOS EFFECTS INITIALIZATION -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
<script>
    AOS.init({
        disable: false, // accepts following values: 'phone', 'tablet', 'mobile', boolean, expression or function
        duration: 750,
        offset: 120,
        easing: 'ease-in-out'
    });
</script>
<!-- SCRIPT FOR FONT AWESOME -->
<script src="https://kit.fontawesome.com/2cf12949d8.js" crossorigin="anonymous"></script>
<!-- jQuery first-->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<!--Popper.js-->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<!--Bootstrap JS-->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script>
  /* Trigger flash modal */
  $(document).ready(function() {
      var messages = "{{ get_flashed_messages() }}";

      if (typeof messages != 'undefined' && messages != '[]') {
          $("#myModal").modal();
      };
  });
</script>
</body>
</html>






</html>

proxcity_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<!-- MAIN CONTENT -->
<section class="banner">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <img class="p-2" src="{{url_for('static', filename='Logo.png')}}" alt="Logo" width="150", height="150">
        <h1>Proxcity</h1>
        <h4 class="py-4">Search for your local service here!</h4>
        
        <div class="container">
          <form class="row mx-auto mb-5 pb-5" action="/results">
            <input id="search-box" name="search-query" type="text" class="form-control col-md-8" placeholder="Search Local Businesses!"/>
            <input id="zip-box" name="zipcode" type="text" pattern="[0-9]{5}" class="form-control col-md-2" placeholder="Zipcode"/>
            <input id="submit" type="submit" class="btn btn-primary col-md-2" value="Search"/>
          </form>
        </div>

      </div>
    </div>
  </div>
  <!--Waves Container-->
  <div>
    <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
    viewBox="0 24 150 28" preserveAspectRatio="none" shape-rendering="auto">
    <defs>
    <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
    </defs>
    <g class="parallax">
    <use xlink:href="#gentle-wave" x="48" y="0" fill="rgba(255,255,255,0.7" />
    <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.5)" />
    <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.3)" />
    <use xlink:href="#gentle-wave" x="48" y="7" fill="#fff" />
    </g>
    </svg>
    </div>
  <!--Waves end-->

</section>
<!-- End Main Content -->

<!-- Three Column Section -->
<section id="services">
  <div class="container text-center">
    <h1 class="title">OUR SERVICES</h1>
    <div class="row text-center">
  
      <div class="col-md-4 my-2 services">
        <img src="/static/search.jpg" alt="" class="service-img w-75">
        <h4 class="my-4">Find</h4>
        <p>Assisting those empowered to support their local businessess 
          is one of our main goals. Using just your zip code and a quick 
          search query, we can connect you to what you're looking for!</p>
      </div>
  
      <div class="col-md-4 my-2 services">
        <img src="/static/help.jpg" alt="" class="service-img w-75">
        <h4 class="my-4">Help</h4>
        <p>The pandemic of 2020 left many small businesses either shut down
          or struggling to stay afloat. Not only do we want to help you
          find what you're looking for, we aim to do our part in assisting
          local businesses. Every visit to a local business helps this cause,
          and we thank you for stopping by to lend a hand!
        </p>
      </div>
  
      <div class="col-md-4 my-2 services">
        <img src="/static/save.jpg" alt="" class="service-img w-75">
        <h4 class="my-4">Save</h4>
        <p>Have an awesome experience at a local business found through
          Proxcity? We provide the capability to save locations to your
          favorites for easy access. Great for spreading much needed 
          word-of-mouth exposure for these diamonds in the rough.
        </p>
      </div>
    </div>
    <a href="{{ url_for('auth.login') }}" class="btn btn-primary btn-md">Get Started</a>
  </div>
</section>

<!-- End Three Column Section -->


<!--Section: Contact v.2-->
<section class="contact mb-4">
  <div class="container">

    <!--Section heading-->
    <h1 class="title text-center">Contact us</h1>
    <!--Section description-->
    <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
        a matter of hours to help you.</p>

    <div class="row">
        <!--Grid column-->
        <div class="col-md-6 m-5">
            <form id="contact-form" name="contact-form" action="mail.php" method="POST">

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="name" name="name" class="form-control">
                            <label for="name" class="">Your name</label>
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="email" name="email" class="form-control">
                            <label for="email" class="">Your email</label>
                        </div>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0">
                            <input type="text" id="subject" name="subject" class="form-control">
                            <label for="subject" class="">Subject</label>
                        </div>
                    </div>
                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form">
                            <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
                            <label for="message">Your message</label>
                        </div>

                    </div>
                </div>
                <!--Grid row-->

            </form>

            <div class="text-center text-md-left">
                <a class="btn btn-primary">Send</a>
            </div>
            <div class="status"></div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 text-center">
          <img src="/static/contact.jpg" alt="" class="service-img w-100">
        </div>
        <!--Grid column-->

    </div>


  </div>
</section>
<!--Section: Contact v.2-->


  {% endblock %}
</div>

proxcity_app/templates/login.html
{% extends 'base.html' %} {% block content %}
<div class="log-content">
  <div class="container p-5">
    <div class="row">
      <div class="col-md-6">
        <img src="/static/login.jpg" alt="" class="w-100" />
      </div>
      <div class="col-md-6 d-flex justify-content-center align-items-center">
        <div class="box">
          <h1 class="text-center p-4 title">Login</h1>
          <form method="POST" action="/login">
            <div class="form-group">
              <label for="email">Email address</label>
              <input
                type="email"
                class="form-control"
                id="email"
                name="email"
                placeholder="Email"
                autofocus=""
              />
              <small id="emailHelp" class="form-text text-muted"
                >We'll never share your email with anyone else.</small
              >
            </div>

            <div class="form-group">
              <label for="password">Password</label>
              <input
                type="password"
                class="form-control"
                id="password"
                name="password"
                placeholder="Password"
              />
            </div>

            <div class="form-check p-1">
              <input
                class="form-check-input"
                type="checkbox"
                value=""
                id="checkbox"
              />
              <label class="form-check-label" for="checkbox">
                Remember me
              </label>
            </div>

            <button type="submit" class="btn btn-primary">Login</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

proxcity_app/templates/results.html
{% extends 'base.html' %} {% block content %}
<div id="form_results">
  <div class="container p-5">
    <div class="row">
      <div class="col-12 text-center">
        <img
          class="p-2"
          src="{{url_for('static', filename='Logo.png')}}"
          alt="Logo"
          width="150"
          ,
          height="150"
        />
        <div class="container p-5">
          <form class="row mx-auto" action="/results">
            <input
              id="search-box"
              name="search-query"
              type="text"
              class="form-control col-md-8"
              placeholder="Search Local Businesses!"
            />
            <input
              id="zip-box"
              name="zipcode"
              type="text"
              pattern="[0-9]{5}"
              class="form-control col-md-2"
              placeholder="Zipcode"
            />
            <input
              id="submit"
              type="submit"
              class="btn btn-primary col-md-2"
              value="Search"
            />
          </form>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        {% for i in range(num_venues) %}
        <!-- Responses Start -->
        <div class="card mb-3 py-4 shadow">
          <div class="row p-1">
            <!-- card image -->
            <div class="col-md-2 text-center">
              <img class="p-2" src="{{photos[i]}}" width="150" ,height="150" />
            </div>
            <!-- card body -->
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{results[i].name}}</h5>
                <p class="card-text">
                  <small class="text-muted"
                    >{{results[i].location.address}}</small
                  >
                </p>
                <p class="card-text">{{desc[i]}}</p>
                <form action="/user" method="POST">
                  <input
                    type="hidden"
                    name="name"
                    value="{{results[i].name}}"
                  />
                  <input
                    type="hidden"
                    name="address"
                    value="{{results[i].location.address}}"
                  />
                  <input type="hidden" name="description" value="{{desc[i]}}" />
                  <input
                    type="hidden"
                    name="photo_path"
                    value="{{photos[i]}}"
                  />
                  <button type="submit" class="btn btn-primary">
                    Add to Favorites
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- Responses End -->
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

proxcity_app/templates/signup.html
{% extends 'base.html' %} {% block content %}
<div class="sign-content">
  <div class="container p-5">
    <div class="row">
      <div class="col-md-6">
        <img src="/static/sign.jpg" alt="" class="w-100">
      </div>
      <div class="col-md-6 d-flex justify-content-center align-items-center">
        <div class="box">
          <h1 class="text-center p-4 title">Sign Up</h1>
          <form method="POST" action="/signup">
            <div class="form-group">
              <label for="email">Email address</label>
              <input type="email" class="form-control" id="email" name="email" placeholder="Email" autofocus="">
              <small id="emailHelp" class="form-text text-muted" >We'll never share your email with anyone else.</small>
            </div>

            <div class="form-group">
              <label for="name">Name</label>
              <input
                type="text"
                class="form-control"
                id="name"
                name="name"
                placeholder="Name"
                autofocus=""
              />
            </div>

            <div class="form-group">
              <label for="password">Password</label>
              <input
                type="password"
                class="form-control"
                id="password"
                name="password"
                placeholder="Password"
              />
            </div>

            <button type="submit" class="btn btn-primary">Sign Up</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

proxcity_app/templates/user.html
{% extends 'base.html' %} {% block content %}
<!--USER INFO -->
<section class="banner">
  <!-- User Profile -->
  <div class="container text-center pb-5">
    <div class="row">
      <div class="col-12">
        <!-- USER CONTENT -->
        <div class="user">
          <i class="fa fa-user-circle fa-10x"></i>
          <div class="user_info">
            <br />
            <h1>{{ user.name }}</h1>
            <p>
              {{ user.email }}
              <br />
              <span>Locations Saved: {{ favorites | length }}</span>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- User Profile End -->

  <!--Waves Container-->
  <div>
    <svg
      class="waves"
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      viewBox="0 24 150 28"
      preserveAspectRatio="none"
      shape-rendering="auto"
    >
      <defs>
        <path
          id="gentle-wave"
          d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"
        />
      </defs>
      <g class="parallax">
        <use
          xlink:href="#gentle-wave"
          x="48"
          y="0"
          fill="rgba(255,255,255,0.7"
        />
        <use
          xlink:href="#gentle-wave"
          x="48"
          y="3"
          fill="rgba(255,255,255,0.5)"
        />
        <use
          xlink:href="#gentle-wave"
          x="48"
          y="5"
          fill="rgba(255,255,255,0.3)"
        />
        <use xlink:href="#gentle-wave" x="48" y="7" fill="#fff" />
      </g>
    </svg>
  </div>
  <!--Waves end-->
</section>

<section class="fav">
  <div class="container">
    <h1 class="title text-center">FAVORITES</h1>
    <div class="row">
      <div class="col-md-12">
        <!-- Responses Start -->
        {% for favorite in favorites %}
        <div class="card mb-3 py-4 shadow">
          <div class="row p-1">
            <!-- card image -->
            <div class="col-md-2 text-center">
              <img
                class="p-2"
                src="{{ favorite.photo_path }}"
                alt="Logo"
                width="150"
                ,
                height="150"
              />
            </div>
            <!-- card body -->
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{ favorite.name }}</h5>
                <p class="card-text">
                  <small class="text-muted">{{ favorite.address }}</small>
                </p>
                <p class="card-text">{{ favorite.description }}</p>
                <form action="/delete" method="POST">
                  <input type="hidden" value="{{favorite._id}}" name="id" />
                  <button type="submit" class="btn btn-primary">Remove</button>
                </form>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        <!-- Responses End -->
      </div>
    </div>
  </div>
</section>

{% endblock %}